name: "AssemblyMod"
description: "Rewrite of FactoryMod for 1.13.2"
authors:
- "aecsocket"
- "Cbelli1352"
- "cheeseburgur101"
- "Quartzic"
- "srikavin"
- "TheNoobWar"
- "Daffeh"
version: 0.0
api-version: 1.13
main: net.teengamingnights.assemblymod.AssemblyMod